// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ghinelli.johan._5h.Ecommerce.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20240525074239_PrimaVersione")]
    partial class PrimaVersione
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ghinelli.johan._5h.Ecommerce.Models.Auto", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chilometraggio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cilindrata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modello")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezzo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auto");
                });

            modelBuilder.Entity("ghinelli.johan._5h.Ecommerce.Models.Utente", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });
#pragma warning restore 612, 618
        }
    }
}
